"""Obfuscation engine initialization."""

from bot.engine.tokenizer import Tokenizer
from bot.engine.parser import Parser
from bot.engine.ast import (
    ASTNode,
    Block,
    Assignment,
    LocalAssignment,
    IfStatement,
    WhileStatement,
    ForStatement,
    ForInStatement,
    FunctionDef,
    BinaryOp,
    UnaryOp,
    FunctionCall,
    Index,
    Property,
    TableConstructor,
    FunctionExpression,
    NumberLiteral,
    StringLiteral,
    BooleanLiteral,
    NilLiteral,
    Identifier,
    ReturnStatement,
    BreakStatement,
)

__all__ = [
    "Tokenizer",
    "Parser",
    "ASTNode",
    "Block",
    "Assignment",
    "LocalAssignment",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "ForInStatement",
    "FunctionDef",
    "BinaryOp",
    "UnaryOp",
    "FunctionCall",
    "Index",
    "Property",
    "TableConstructor",
    "FunctionExpression",
    "NumberLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NilLiteral",
    "Identifier",
    "ReturnStatement",
    "BreakStatement",
]
