"""Runtime Lua code for obfuscated scripts."""

RUNTIME_CODE = r'''
-- Obfuscated script runtime support
-- Generated by ObfBot

local __OBFBOT_VERSION = "1.0.0"
local __RUNTIME_ACTIVE = true

-- String decryption function
local __string_key = "{key}"
local function __decrypt_string(encrypted_hex)
    local result = ""
    local key_bytes = {}
    for i = 1, #__string_key do
        key_bytes[i] = string.byte(__string_key, i)
    end
    
    for i = 1, #encrypted_hex, 2 do
        local byte_val = tonumber(encrypted_hex:sub(i, i+1), 16)
        local key_index = ((i // 2 - 1) % #key_bytes) + 1
        result = result .. string.char(byte_val ~ key_bytes[key_index])
    end
    return result
end

-- Anti-debug functions
local __debug_detected = false

local function __check_debug()
    if debug and debug.getinfo then
        return true
    end
    if debug and debug.gethook then
        return true
    end
    return false
end

local function __validate_environment()
    -- Check for environment modifications
    local _G_backup = {}
    local suspicious = false
    
    -- Check common library modifications
    if _G.loadstring and type(_G.loadstring) ~= "function" then
        suspicious = true
    end
    
    return not suspicious
end

-- Integrity check
local __script_hash = "{hash}"
local __modification_detected = false

local function __check_integrity()
    -- This would normally verify script integrity
    return true
end

-- Anti-tamper detection
local __tamper_callbacks = {}

local function __register_tamper_callback(callback)
    table.insert(__tamper_callbacks, callback)
end

local function __trigger_tamper_detection()
    __modification_detected = true
    for _, callback in ipairs(__tamper_callbacks) do
        callback()
    end
end

-- Opaque predicates
local function __opaque_predicate_1()
    return (0xDEADBEEF % 2) == 1
end

local function __opaque_predicate_2()
    return (string.len(__string_key) > 0)
end

-- Dummy functions for added confusion
local function __dummy_1() end
local function __dummy_2() end
local function __dummy_3() end
local function __dummy_4() end

-- Main initialization
if __check_debug() then
    __debug_detected = true
end

if not __validate_environment() then
    error("Environment validation failed")
end

-- Entry point
local __entry_point = function()
    -- User code will be inserted here
end

return __entry_point
'''


def get_runtime_code(key: str = "", hash: str = "") -> str:
    """Get runtime code with parameters.

    Args:
        key: String encryption key
        hash: Script hash for integrity

    Returns:
        Runtime code
    """
    return RUNTIME_CODE.format(key=key or "default_key", hash=hash or "")
